services:

  postgres:
    image: postgres:17

    container_name: foodapp-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: foodapp

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .

    container_name: foodapp-backend

    depends_on:
      - postgres

    environment:
      PORT: 5000
      JWT_SECRET: mysecretkey123

    ports:
      - "5000:5000"

volumes:
  postgres_data: